Feature/1-interaction-protocol
yarnaid/infection_spread pull request #11
Opened 2021-07-05 22:03 UTC by PopeyeTheSailorsCat

I think I need to show my work already at this stage. Since I seem to have implemented what was intended, but whether I understood it correctly and whether I implemented it correctly, I do not know.

2021-07-06 07:42 UTC, yarnaid requested changes

2021-07-06 07:42 UTC, yarnaid commented on gRPC/spec.proto
> +        SUCCESS = 0;
The first value will be the default. Let's use this UNDEFINED in addition to others

2021-07-06 07:42 UTC, yarnaid commented on gRPC/spec.proto
> +    int32  request_id = 2;
Let's use UUID for this. In our case, will be enough just a string without any validation
Also, let's put `request_id` to the Meta message

2021-07-06 07:42 UTC, yarnaid commented on gRPC/spec.proto
> +        int32 id=1; //unique key
These values are duplicated from the `State` massage. Let's make a bit more complex structure.
We can use something like `BaseUnit` to store universal values for each entity and then extend them

2021-07-06 07:42 UTC, yarnaid commented on gRPC/spec.proto
> +        int32 type = 2; // building specification (house, road, clinic)
why the type is int?

2021-07-06 07:42 UTC, yarnaid commented on tests/client_server.py
> +import unittest
let's use `pytest`

2021-07-06 07:42 UTC, yarnaid commented on backend/server.py
> +                                   request_id=request.meta.request_id)
let's use [this](https://pypi.org/project/pure-protobuf/) to simplify massages processing

2021-07-06 07:42 UTC, yarnaid commented on backend/server.py
> +                                       ))
Let's follow [MVC](https://en.wikipedia.org/wiki/Model%E2%80%93view%E2%80%93controller). Models are our messages, views are a request-response server and controllers we must extract from the views leyer

2021-07-06 07:42 UTC, yarnaid commented on backend/server.py
> +    server = grpc.server(futures.ThreadPoolExecutor(max_workers=10))
[cpu count](https://devdocs.io/python~3.8/library/os#os.cpu_count)

2021-07-06 07:42 UTC, yarnaid commented on backend/server.py
> +    logging.basicConfig()
Let's create a dedicated logger for each file. It makes debugging simpler. Also, usage of logging module is not the best practice

2021-07-06 07:42 UTC, yarnaid commented on frontend/client.py
> +from __future__ import print_function
let's rename this to `echo_client` and add debug output. For FE we will have another client)

2021-07-06 07:44 UTC, yarnaid commented
Great start, thank you! Could you also add a `Makefile` to simplify and unify the run? Please, add there commands for grpc code generation, running test with/without coverage

2021-07-07 14:28 UTC, yarnaid requested changes

2021-07-07 14:28 UTC, yarnaid commented on Makefile
> +test-no-coverage:
let's call this just `test`

2021-07-07 14:28 UTC, yarnaid commented on dataStructure/gRPC.py
> +        return RequestCounter.id
let's use [this](https://devdocs.io/python~3.8/library/itertools#itertools.count)

2021-07-07 14:28 UTC, yarnaid commented on dataStructure/gRPC.py
> +    DEAD = 3
👍

2021-07-07 14:28 UTC, yarnaid commented on dataStructure/gRPC.py
> +class State:
class name `State` can be a bit confusing. Could you make it more exact

2021-07-07 14:28 UTC, yarnaid commented on dataStructure/gRPC.py
> +    building: Building = field(2)
I think that it should be an array

2021-07-07 14:54 UTC, yarnaid commented on dataStructure/gRPC.py
> +# gRPC_building_types = {'HOUSE': 0, 'ROAD': 1}
let's remove comments

2021-07-08 08:16 UTC, PopeyeTheSailorsCat commented on gRPC/spec.proto
> +    int32  request_id = 2;
Done

2021-07-08 08:16 UTC, PopeyeTheSailorsCat commented on backend/server.py
> +                                       ))
Done(excluding echo_client)

2021-07-08 08:16 UTC, PopeyeTheSailorsCat commented on backend/server.py
> +    logging.basicConfig()
Done

2021-07-08 08:16 UTC, PopeyeTheSailorsCat commented on Makefile
> +test-no-coverage:
Done

2021-07-08 08:16 UTC, PopeyeTheSailorsCat commented on dataStructure/gRPC.py
> +        return RequestCounter.id
Done

2021-07-08 08:17 UTC, PopeyeTheSailorsCat commented on dataStructure/gRPC.py
> +class State:
Done

2021-07-08 08:17 UTC, PopeyeTheSailorsCat commented on dataStructure/gRPC.py
> +# gRPC_building_types = {'HOUSE': 0, 'ROAD': 1}
Done

2021-07-08 11:56 UTC, PopeyeTheSailorsCat commented on dataStructure/gRPC.py
> +    building: Building = field(2)
Done

2021-07-08 16:59 UTC, yarnaid requested changes

2021-07-08 16:59 UTC, yarnaid commented on backend/server.py
> +        self.model_objects = model_objects
could you rename this variable to be more clear

2021-07-08 16:59 UTC, yarnaid commented on frontend/client.py
> +def update_request(stub):  # Request to update the states of modeling objects
please, replace these comments with docstrings

2021-07-08 17:33 UTC, PopeyeTheSailorsCat commented on backend/server.py
> +        self.model_objects = model_objects
Done

2021-07-08 17:33 UTC, PopeyeTheSailorsCat commented on frontend/client.py
> +def update_request(stub):  # Request to update the states of modeling objects
Dobe?

2021-07-09 20:58 UTC, merged