Feature/2 mock backend
yarnaid/infection_spread pull request #13
Opened 2021-07-08 13:06 UTC by YaroslavAggressive

2021-07-08 13:32 UTC, PopeyeTheSailorsCat commented on backend/map_generation.py
> +    STREET = 3
In dataStructure.gRPC already exist BuildingType

2021-07-08 13:32 UTC, PopeyeTheSailorsCat commented on backend/map_generation.py
> +
ModelingServicer at initialization gets iterators for all people and for all objects on the map, maps iterator expected to have method .size() -> width, length
There are several ways to implement this, I'm just telling you what data is expected

2021-07-08 15:02 UTC, PopeyeTheSailorsCat commented
It seems that it would be reasonable to merge this branch with feature-1. The latest versions of feature-1 describe loggers, in addition, it is more convenient to develop a mock knowing the latest (possibly final) version of what it will interact with.
But of course it is safer to wait for the results of the pull request feature-1

2021-07-08 15:30 UTC, YaroslavAggressive commented on backend/map_generation.py
> +
But in this case it is necessary to separate buildings and people in two different classes. We can't iterate over two lists, can we?

2021-07-08 15:50 UTC, YaroslavAggressive commented on backend/map_generation.py
> +
Updated

2021-07-09 21:26 UTC, yarnaid requested changes

2021-07-09 21:26 UTC, yarnaid commented on backend/config_parser.py
> +        return model_parameters
let's use python [native libraries](https://devdocs.io/python~3.8/library/configparser)

2021-07-09 21:26 UTC, yarnaid commented on backend/map_generation.py
> +            yield elem
why do we need iterators?

2021-07-09 21:26 UTC, yarnaid commented on backend/map_generation.py
> +        return self.get_map_length(), self.get_map_width()
it's a bad practice to return several values

2021-07-09 21:26 UTC, yarnaid commented on backend/map_generation.py
> +INDENT_FROM_BORDERS = 3  # indent from city borders
Let's move these values to the config

2021-07-09 21:26 UTC, yarnaid commented on backend/map_generation.py
> +    def create_generation_list(self):  # generating population of the city
let's use docstrings or better write obvious unambiguous names

2021-07-09 21:26 UTC, yarnaid commented on backend/map_generation.py
> +            rand.seed(datetime.datetime.now().microsecond)
are you sure we need this in each iteration?

2021-07-09 21:26 UTC, yarnaid commented on backend/map_generation.py
> +            return False  # while we handle the error of object types in this way
let's use assertions instead of this

2021-07-09 21:26 UTC, yarnaid commented on backend/map_generation.py
> +
[DRY](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself)

2021-07-09 21:26 UTC, yarnaid commented on backend/map_generation.py
> +    #     pass  # need to be completed
please, remove these comments if we don't need them now

2021-07-09 21:26 UTC, yarnaid commented on backend/map_generation.py
> +        return self.__y
Let's use [dataclass](https://devdocs.io/python~3.8/library/dataclasses#dataclasses.dataclass) for this

2021-07-09 21:26 UTC, yarnaid commented on backend/map_generation.py
> +        self.__human_type = HumanType.NORMAL
hmm, is this class useful? It has now public methods

2021-07-09 21:41 UTC, PopeyeTheSailorsCat commented on backend/map_generation.py
> +        return self.get_map_length(), self.get_map_width()
My bad, I asked for this. I will divide it into the width and length methods

2021-07-09 21:44 UTC, PopeyeTheSailorsCat commented on backend/map_generation.py
> +            yield elem
backend.server.ModelingService expect at initialization 
:param map_obj: iterable obj : obj from which we can read map objects
:param human_objects: iterable obj : obj from which we can read humans object

2021-07-09 21:44 UTC, PopeyeTheSailorsCat commented on backend/map_generation.py
> +        return self.get_map_length(), self.get_map_width()
My bad, I asked for this. I will divide it into the width and length methods

2021-07-09 21:48 UTC, PopeyeTheSailorsCat commented on backend/map_generation.py
> +        return self.get_map_length(), self.get_map_width()
Oh, these two methods already exist. Then I will rename them, change their call to server and delete size

2021-07-10 10:10 UTC, YaroslavAggressive commented on backend/map_generation.py
> +            rand.seed(datetime.datetime.now().microsecond)
This is my reassurance based on the experience of working on C, there the random number generator is pseudo-random, and for it you need to change the seed at each iteration

2021-07-10 10:12 UTC, YaroslavAggressive commented on backend/map_generation.py
> +        self.__human_type = HumanType.NORMAL
In the future we will need to move people around the map, I think it will be more convenient to implement this using methods in this class

2021-07-10 10:13 UTC, YaroslavAggressive commented on backend/map_generation.py
> +        return self.__y
Done

2021-07-10 10:13 UTC, YaroslavAggressive commented on backend/map_generation.py
> +    #     pass  # need to be completed
Done

2021-07-10 10:13 UTC, YaroslavAggressive commented on backend/map_generation.py
> +            return False  # while we handle the error of object types in this way
Done

2021-07-10 10:13 UTC, YaroslavAggressive commented on backend/map_generation.py
> +    def create_generation_list(self):  # generating population of the city
Done

2021-07-10 10:13 UTC, YaroslavAggressive commented on backend/map_generation.py
> +INDENT_FROM_BORDERS = 3  # indent from city borders
Done

2021-07-10 11:25 UTC, YaroslavAggressive commented on backend/config_parser.py
> +        return model_parameters
Done

2021-07-10 11:27 UTC, YaroslavAggressive commented on backend/map_generation.py
> +
Done (but i'm not sure that i understtod correct what needs to be fixed)

2021-07-11 14:05 UTC, PopeyeTheSailorsCat commented on tests/test_backend.py
> +    answer = test_data[2]
first_building, second_building, answer, *_ = test_data
[howto](https://stackabuse.com/unpacking-in-python-beyond-parallel-assignment)

2021-07-11 14:17 UTC, yarnaid commented on backend/map_generation.py
> +            yield elem
It's not an iterator, it's a generator)

2021-07-11 14:25 UTC, yarnaid commented on backend/map_generation.py
> +            rand.seed(datetime.datetime.now().microsecond)
generally, we don't need this in python

2021-07-11 14:37 UTC, yarnaid requested changes

2021-07-11 14:37 UTC, yarnaid commented on backend/map_generation.py
> +            human_objects.append(Human(BaseUnit(self.__id_counter, human_x, human_y)))
Let's make auto-tracking and assignment inside `BaseUnit`

2021-07-11 14:37 UTC, yarnaid commented on backend/map_generation.py
> +        assert isinstance(second_building, Building), "Invalid type of second input arguments"
messages are not infomative

2021-07-11 14:37 UTC, yarnaid commented on backend/map_generation.py
> +                    second_building.base.coord_y + second_building.width / 2]
DRY, let's use one code here

2021-07-11 14:37 UTC, yarnaid commented on backend/map_generation.py
> +    __base: BaseUnit
why not inheritance?

2021-07-11 14:37 UTC, yarnaid commented on backend/map_generation.py
> +    __human_type: HumanType = HumanType.NORMAL
why not public?
Also, `type` IMO better replace health status

2021-07-12 12:36 UTC, YaroslavAggressive commented on backend/map_generation.py
> +    __base: BaseUnit
Changed this, now Building and HumanState are inherited from BaseUnit. But initially there was no inheritance, most likely because default values ​​were set only for the baseunit fields, and during inheritance you would have to set such values ​​for all fields of the HumanState and Building classes

2021-07-12 12:38 UTC, YaroslavAggressive commented on backend/map_generation.py
> +    __human_type: HumanType = HumanType.NORMAL
Done (My mistake, here the privacy of the fields is not needed. Removed this class and used HumanState instead of it. And changed enum class name corresponding field in the class HumanState)

2021-07-12 12:38 UTC, YaroslavAggressive commented on backend/map_generation.py
> +                    second_building.base.coord_y + second_building.width / 2]
Done

2021-07-12 12:39 UTC, YaroslavAggressive commented on backend/map_generation.py
> +        assert isinstance(second_building, Building), "Invalid type of second input arguments"
Done (updated with method for creating error message for each assertion)

2021-07-12 12:39 UTC, YaroslavAggressive commented on tests/test_backend.py
> +    answer = test_data[2]
Done

2021-07-12 12:40 UTC, YaroslavAggressive commented on backend/map_generation.py
> +            human_objects.append(Human(BaseUnit(self.__id_counter, human_x, human_y)))
Done (but there are some problem with comparing protobuf types)

2021-07-12 12:44 UTC, YaroslavAggressive commented on backend/map_generation.py
> +            human_objects.append(Human(BaseUnit(self.__id_counter, human_x, human_y)))
@yarnaid or @PopeyeTheSailorsCat, Maybe you know what can be used to solve this problem?

2021-07-12 14:15 UTC, PopeyeTheSailorsCat commented on backend/map_generation.py
> +            yield elem
Well, of course, yes, but we can iterate on it!
I'll rename it

2021-07-12 14:26 UTC, PopeyeTheSailorsCat commented on dataStructure/gRPC.py
> +    #         .format(self.coord_y.__class__.__name__, int32.__name__)
Is this still necessary?

2021-07-12 14:36 UTC, YaroslavAggressive commented on dataStructure/gRPC.py
> +    #         .format(self.coord_y.__class__.__name__, int32.__name__)
Hm, no, i forgot to delete this comment block. Done

2021-07-12 16:35 UTC, yarnaid requested changes
Please, also add type annotations for all functions

2021-07-12 16:35 UTC, yarnaid commented on backend/map_generation.py
> +    def __init__(self, config_name: str):  # map object constructor for research
please, use docstrings everywhere instead of comments

2021-07-12 16:35 UTC, yarnaid commented on backend/map_generation.py
> +        # why 5-written in the comment above
??

2021-07-12 16:35 UTC, yarnaid commented on backend/map_generation.py
> +        buildings_quantity = self.config_data[ConfigParameters.BUILDINGS_QUANTITY.value]
Let's simplify access to configurations

2021-07-12 16:35 UTC, yarnaid commented on backend/config_parser.py
> +
Let's use a dataclass for configuration instead of enum and dict

2021-07-12 16:35 UTC, yarnaid commented on backend/map_generation.py
> +# depending on the length / width of the random card
please, move this comment to the file's docstring or just to the place where it's actual

2021-07-12 16:35 UTC, yarnaid commented on backend/map_generation.py
> +        self.__wall_len_limit = self.config_data[ConfigParameters.MAP_LENGTH.value] // 5
we must not have any magic numbers in the code. I should be moved to configs or constants

2021-07-12 16:35 UTC, yarnaid commented on backend/map_generation.py
> +        self.__id_counter = 0
`itertools.count`

2021-07-12 16:35 UTC, yarnaid commented on backend/map_generation.py
> +        self.__id_counter = 0
do we need this? ids still not assigned during initialisation building?

2021-07-12 16:35 UTC, yarnaid commented on backend/map_generation.py
> +            yield elem
if a function returns a list, we can just return `iter(list)` to have an iterator instead of an additional generator

2021-07-12 16:35 UTC, yarnaid commented on backend/map_generation.py
> +                        and iterations < self.config_data[ConfigParameters.ITERATION_CONSTRAINT.value]:
next(iteration) < max_iteration, where iteration = itertools.count()

2021-07-12 16:35 UTC, yarnaid commented on backend/map_generation.py
> +            new_building = ResearchMap.create_building_parameters(self.__wall_len_limit, self.config_data,
Please, align the names of variables and functions: create_building_parameters why it returns the building instead of parameters? Or maybe from_parameters?

2021-07-12 16:35 UTC, yarnaid commented on backend/map_generation.py
> +                    self.__id_counter += 1
this algorithm can be very slow. We must optimize it in the future

2021-07-12 16:35 UTC, yarnaid commented on backend/map_generation.py
> +    @staticmethod
we pass to this function 2 constants and one class variable. Let's convert it to class method

2021-07-12 16:35 UTC, yarnaid commented on backend/map_generation.py
> +        return Building(id_counter, x, y, BuildingType.HOUSE, int32(width), int32(length), int32(angle))
coordinates are still int?

2021-07-12 16:35 UTC, yarnaid commented on backend/map_generation.py
> +            human_objects.append(HumanState(int32(self.__id_counter), human_x, human_y, HealthStatus.NORMAL))
I think that generation of a random person must be implemented in the Human class

2021-07-12 16:35 UTC, yarnaid commented on backend/map_generation.py
> +        return Building(id_counter, x, y, BuildingType.HOUSE, int32(width), int32(length), int32(angle))
Please, move random building generation to the Building class

2021-07-12 16:35 UTC, yarnaid commented on backend/map_generation.py
> +                   and max(second_bounds['y']) >= min(first_bounds['y'])
I think this method maybe a part of the Building class

2021-07-12 16:35 UTC, yarnaid commented on backend/map_generation.py
> +        return dict({'x': x_bounds, 'y': y_bounds})
let's move it to the Building also, we can use a dataclass bounds or better just have an access to these values from a building

2021-07-12 16:35 UTC, yarnaid commented on backend/map_generation.py
> +                                                                                  expected_type.__name__)
let's remove this with intersection_check to another class

2021-07-12 16:35 UTC, yarnaid commented on backend/map_generation.py
> +    def has_intersection(buildings_list, new_building):
you can remove staticmethod if use class variable buildings

2021-07-12 16:35 UTC, yarnaid commented on backend/map_generation.py
> +        return self.config_data[ConfigParameters.MAP_WIDTH.value]
let's move these values to the class variables

2021-07-12 17:51 UTC, YaroslavAggressive commented on backend/map_generation.py
> +            yield elem
Done

2021-07-12 19:03 UTC, YaroslavAggressive commented on backend/map_generation.py
> +        return Building(id_counter, x, y, BuildingType.HOUSE, int32(width), int32(length), int32(angle))
Done

2021-07-12 20:53 UTC, YaroslavAggressive commented on backend/map_generation.py
> +# depending on the length / width of the random card
Done (comment moved into description of current attribute of object)

2021-07-12 21:10 UTC, YaroslavAggressive commented on backend/map_generation.py
> +        # why 5-written in the comment above
Done (removed this comment)

2021-07-12 21:54 UTC, YaroslavAggressive commented on backend/map_generation.py
> +    def __init__(self, config_name: str):  # map object constructor for research
Done

2021-07-12 22:17 UTC, YaroslavAggressive commented on backend/map_generation.py
> +        return dict({'x': x_bounds, 'y': y_bounds})
Done (moved this method into Building-class and separated bounds as 'get_y_bounds' and 'get_x_bounds' + added private attributes for x- and y- bounds)

2021-07-12 22:19 UTC, YaroslavAggressive commented on backend/map_generation.py
> +                   and max(second_bounds['y']) >= min(first_bounds['y'])
Done

2021-07-12 22:21 UTC, YaroslavAggressive commented on backend/map_generation.py
> +                                                                                  expected_type.__name__)
Done

2021-07-12 22:40 UTC, YaroslavAggressive commented on backend/map_generation.py
> +        self.__wall_len_limit = self.config_data[ConfigParameters.MAP_LENGTH.value] // 5
Done (moved this divider to configurations)

2021-07-12 23:14 UTC, YaroslavAggressive commented on backend/map_generation.py
> +            new_building = ResearchMap.create_building_parameters(self.__wall_len_limit, self.config_data,
Done (updated method name)

2021-07-12 23:23 UTC, YaroslavAggressive commented on backend/map_generation.py
> +    def has_intersection(buildings_list, new_building):
Done

2021-07-12 23:29 UTC, YaroslavAggressive commented on backend/map_generation.py
> +        return self.config_data[ConfigParameters.MAP_WIDTH.value]
Done

2021-07-12 23:46 UTC, YaroslavAggressive commented on backend/map_generation.py
> +            human_objects.append(HumanState(int32(self.__id_counter), human_x, human_y, HealthStatus.NORMAL))
Done

2021-07-13 17:11 UTC, YaroslavAggressive commented on backend/map_generation.py
> +    @staticmethod
Maybe, if it is better to transfer this method to a class, then it is worth leaving it static and just transfer all the necessary parameters to it?

2021-07-13 17:24 UTC, YaroslavAggressive commented on backend/map_generation.py
> +        return Building(id_counter, x, y, BuildingType.HOUSE, int32(width), int32(length), int32(angle))
Done

2021-07-13 17:51 UTC, YaroslavAggressive commented on backend/map_generation.py
> +                        and iterations < self.config_data[ConfigParameters.ITERATION_CONSTRAINT.value]:
Done

2021-07-13 18:05 UTC, YaroslavAggressive commented on backend/map_generation.py
> +        self.__id_counter = 0
Initially, I assumed that ids are assigned to objects on the map during their initialization. So added this counter as object field to assign ids to both buildings and people on map. for example, if in the future the population of people on the map can expand, you can simply pass next(self.id_counter)

2021-07-13 18:07 UTC, YaroslavAggressive commented on backend/map_generation.py
> +        self.__id_counter = 0
Done (added itertools instead of counter in C-style, but it can be replaced later)

2021-07-14 07:50 UTC, yarnaid requested changes

2021-07-14 07:50 UTC, yarnaid commented on backend/config_parser.py
> +    WALL_LENGTH_DIVIDER = "wall_length_divider"
I mean dataclass must be a config class instead of storing keys of variables

2021-07-14 07:50 UTC, yarnaid commented on backend/config_parser.py
> +            processed_config.update({key: int(config.defaults().get(key))})
why int only?

2021-07-14 07:50 UTC, yarnaid commented on backend/map_generation.py
> +        self.__id_counter = count()
please, make assignment of ids automatical during instances initialization

2021-07-14 07:50 UTC, yarnaid commented on backend/map_generation.py
> +        return iter(self.get_population())
now they are iterators) Are you sure we need them? We can just call iter in the places, where we use buildings and people

2021-07-14 07:50 UTC, yarnaid commented on backend/map_generation.py
> +                                                    self.map_width)
hmm, in this method we use only parameters from settings. Let's move them to the building class. In this case, we can just call something like Building.new()

2021-07-14 07:50 UTC, yarnaid commented on backend/map_generation.py
> +                if iterations < self.config_data[ConfigParameters.ITERATION_CONSTRAINT.value]:
you cannot compare generator with int

2021-07-14 07:50 UTC, yarnaid commented on backend/map_generation.py
> +            human_objects.append(HumanState.generate_random_human(self.length(), self.width(), self.__id_counter))
the same as a new building

2021-07-14 07:50 UTC, yarnaid commented on backend/map_generation.py
> +            if Building.intersection_check(building, self):
as I see the second argument must be a list of the buildings
Also, it's better to make not a class method, but instance method to check intersection with only one another bulding

2021-07-14 07:50 UTC, yarnaid commented on backend/map_generation.py
> +        return self.map_width
do we need these methods if they just return a public value?

2021-07-14 07:50 UTC, yarnaid commented on dataStructure/gRPC.py
> +                                                                                  expected_type.__name__)
please, check it

2021-07-14 08:12 UTC, yarnaid commented on backend/map_generation.py
> +        self.__human_type = HumanType.NORMAL
generally, we don't need to move people for spreading calculation) We will use infection function only inside buildings and transport)
Movements on the street are only for animation)

2021-07-14 08:12 UTC, yarnaid commented on backend/map_generation.py
> +        self.__human_type = HumanType.NORMAL
anyway to draw a person we must know his position

2021-07-14 08:13 UTC, yarnaid commented on backend/map_generation.py
> +            human_objects.append(Human(BaseUnit(self.__id_counter, human_x, human_y)))
redefine __new__ method for the BaseUnit class

2021-07-14 08:54 UTC, YaroslavAggressive commented on backend/map_generation.py
> +                if iterations < self.config_data[ConfigParameters.ITERATION_CONSTRAINT.value]:
Done

2021-07-14 10:00 UTC, YaroslavAggressive commented on backend/map_generation.py
> +            rand.seed(datetime.datetime.now().microsecond)
Sorry, missed this comment earlier. Done

2021-07-14 10:53 UTC, YaroslavAggressive commented on backend/map_generation.py
> +    def has_intersection(buildings_list, new_building):
Made the method back static because it initially uses a non-class object variable. This variable is assigned a value only after generating the list of buildings (as seen in __init__)

2021-07-14 10:57 UTC, YaroslavAggressive commented on backend/map_generation.py
> +            if Building.intersection_check(building, self):
Done

2021-07-14 11:49 UTC, YaroslavAggressive commented on backend/map_generation.py
> +        self.__id_counter = count()
Done

2021-07-14 19:47 UTC, YaroslavAggressive commented on backend/map_generation.py
> +        return self.map_width
Done (removed this redundant methods)

2021-07-14 19:47 UTC, YaroslavAggressive commented on dataStructure/gRPC.py
> +                                                                                  expected_type.__name__)
Done (added missing 'return')

2021-07-14 22:41 UTC, YaroslavAggressive commented on backend/config_parser.py
> +    WALL_LENGTH_DIVIDER = "wall_length_divider"
Done

2021-07-14 22:41 UTC, YaroslavAggressive commented on backend/config_parser.py
> +
Done

2021-07-14 22:43 UTC, YaroslavAggressive commented on backend/map_generation.py
> +        buildings_quantity = self.config_data[ConfigParameters.BUILDINGS_QUANTITY.value]
Done (after replacing the config class with dataclass access is automatically simplified)

2021-07-14 22:46 UTC, YaroslavAggressive commented on backend/config_parser.py
> +            processed_config.update({key: int(config.defaults().get(key))})
Done (added a cast to the type obtained directly from the type annotations instead of method from comment)

2021-07-22 16:18 UTC, merged