Feature/3 basic-fe-qt
yarnaid/infection_spread pull request #14
Opened 2021-07-09 12:43 UTC by PopeyeTheSailorsCat

I used QPixMap and QPainter for rendering.

2021-07-11 14:38 UTC, yarnaid commented
Please, merge this branch with main

2021-07-12 17:26 UTC, yarnaid requested changes
1. type annotations
2. all magic numbers to constants/configs
3. all instances we draw, must be objects (classes)

2021-07-12 17:26 UTC, yarnaid commented on frontend/UI/infection_spread_ui.py
> +
You don't need this in python3

2021-07-12 17:26 UTC, yarnaid commented on frontend/UI/infection_spread_ui.py
> +# run again.  Do not edit this file unless you know what you are doing.
docstring

2021-07-12 17:26 UTC, yarnaid commented on frontend/UI_client.py
> +logger = logging.getLogger(__name__)
\_\_name\_\_ -> \_\_file\_\_

2021-07-12 17:32 UTC, PopeyeTheSailorsCat commented on frontend/UI/infection_spread_ui.py
> +# run again.  Do not edit this file unless you know what you are doing.
All this generic file created by command: pyuic5 frontend/UI/infection-spread.ui -o frontend/UI/infection_spread_ui.py
It is said in text ": Any manual changes made to this file will be lost when pyuic5 is
# run again."

2021-07-12 17:34 UTC, yarnaid requested changes
Please, remove obvious parameters documentation

2021-07-12 17:34 UTC, yarnaid commented on frontend/UI_client.py
> +from PyQt5.QtCore import Qt, QRectF, QPoint, QSizeF, QPointF
maybe just import PyQt5?)

2021-07-12 17:34 UTC, yarnaid commented on frontend/UI_client.py
> +        logger.info("Draw dummy random map")
create logger instance

2021-07-12 17:34 UTC, yarnaid commented on frontend/UI_client.py
> +        self.create_human(x, y, human_type)
looks enough strange when you create coordinates and then call the function create_human. I think the body of this function should be in the create_human and here body from current create_human

2021-07-12 17:34 UTC, yarnaid commented on frontend/UI_client.py
> +        :return:
these parameters are obvious and don't require explanations

2021-07-12 17:34 UTC, yarnaid commented on Makefile
> +	pyuic5 frontend/UI/infection-spread.ui -o frontend/UI/infection_spread_ui.py
please, add a run ui target

2021-07-12 17:34 UTC, PopeyeTheSailorsCat commented on frontend/UI/infection_spread_ui.py
> +
All this generic file created by command: pyuic5 frontend/UI/infection-spread.ui -o frontend/UI/infection_spread_ui.py
It is said in text ": Any manual changes made to this file will be lost when pyuic5 is run again'

2021-07-12 17:46 UTC, PopeyeTheSailorsCat commented on frontend/UI_client.py
> +        logger.info("Draw dummy random map")
logging.basicConfig(format='%(relativeCreated)5d %(name)-15s %(levelname)-8s %(message)s')
logger = logging.getLogger(__name__)

I have already created(line 134-135)

> Loggers have the following attributes and methods. Note that Loggers should NEVER be instantiated directly, but always through the module-level function logging.getLogger(name). [logging](https://docs.python.org/3/library/logging.html)

2021-07-12 18:30 UTC, PopeyeTheSailorsCat commented on frontend/UI_client.py
> +logger = logging.getLogger(__name__)
Should i fix this in files from pull-req 1, where i also used _name_?

Done

2021-07-12 18:30 UTC, PopeyeTheSailorsCat commented on frontend/UI_client.py
> +from PyQt5.QtCore import Qt, QRectF, QPoint, QSizeF, QPointF
Done

2021-07-12 18:31 UTC, PopeyeTheSailorsCat commented on frontend/UI_client.py
> +        :return:
Done

2021-07-12 18:43 UTC, PopeyeTheSailorsCat commented on frontend/UI_client.py
> +from PyQt5.QtCore import Qt, QRectF, QPoint, QSizeF, QPointF
Done

2021-07-12 18:52 UTC, PopeyeTheSailorsCat commented on Makefile
> +	pyuic5 frontend/UI/infection-spread.ui -o frontend/UI/infection_spread_ui.py
Can you say more precisely what i need to do? 
The only thing i can find is -x parameter so that generated file can be run as application [pyuic5 docs](https://doc.bccnsoft.com/docs/PyQt5/designer.html#pyuic5)

2021-07-12 21:16 UTC, PopeyeTheSailorsCat commented on frontend/UI_client.py
> +        self.create_human(x, y, human_type)
done
And do same with buildings

2021-07-14 08:09 UTC, yarnaid requested changes

2021-07-14 08:09 UTC, yarnaid commented on backend/server.py
> +    def create_update_response(request, humans) -> UpdateResponse:  # create pb2 object
what about request and humans annotation? (here and here after)

2021-07-14 08:09 UTC, yarnaid commented on backend/server.py
>                          request_id=int32(request.meta.request_id), UUID=str(uuid.uuid1()))
why uuid1? Usually, everywhere uuid4 is used

2021-07-14 08:09 UTC, yarnaid commented on backend/server.py
>          self.human_objects = human_objects
if it's iterators, they shouldn't be named `_obj`
Are you sure we need to store them?

2021-07-14 08:09 UTC, yarnaid commented on backend/server.py
> +        return self.serializer.create_get_map_response(request, map_w, map_l, self.map)
`create_get_map_response` uses 4 parameters and 3 last can be squeezed to self.map only

2021-07-14 08:09 UTC, yarnaid commented on frontend/UI/infection_spread_ui.py
> +
hmm, maybe we can specify there python's version during generation?

2021-07-14 08:09 UTC, yarnaid commented on frontend/UI_client.py
> +        pass
let's raise NotImplementedError or mark this method as abstract to disallow call it

2021-07-14 08:09 UTC, yarnaid commented on frontend/UI_client.py
> +        self.buildings = list()
[] is better (it's a bit faster 😄 )

2021-07-14 08:09 UTC, yarnaid commented on frontend/UI_client.py
> +            print(ex)
why only print?

2021-07-14 08:09 UTC, yarnaid commented on frontend/UI_client.py
> +        return BuildingRectangle(rand_x, rand_y, rand_width, rand_length, DEFAULT_ANGLE)
we already have such method in the #2

2021-07-14 08:09 UTC, yarnaid commented on frontend/UI_client.py
> +        return HumanDote(x, y, human_type)
see above

2021-07-14 08:09 UTC, yarnaid commented on frontend/UI_client.py
> +    w_size, l_size = 800, 600  # ONLY FOR DEBUG
let's paste here real values from config if it's a PR to the main branch

2021-07-14 08:09 UTC, yarnaid commented on frontend/UI_config_parser.py
> +        return processed_config
https://github.com/yarnaid/infection_spread/pull/13/files#r669360826

2021-07-14 08:09 UTC, yarnaid commented on frontend/echo_client.py
>      # run_update()
as I see this code is not used

2021-07-14 11:36 UTC, PopeyeTheSailorsCat commented on frontend/UI_client.py
> +        self.buildings = list()
Done

2021-07-14 11:47 UTC, PopeyeTheSailorsCat commented on frontend/echo_client.py
>      # run_update()
Done

2021-07-14 11:52 UTC, PopeyeTheSailorsCat commented on backend/server.py
> +        return self.serializer.create_get_map_response(request, map_w, map_l, self.map)
Done

2021-07-14 11:52 UTC, PopeyeTheSailorsCat commented on frontend/UI_client.py
> +        pass
Done

2021-07-14 12:16 UTC, PopeyeTheSailorsCat commented on backend/server.py
>                          request_id=int32(request.meta.request_id), UUID=str(uuid.uuid1()))
Done

2021-07-14 14:14 UTC, PopeyeTheSailorsCat commented on backend/server.py
>          self.human_objects = human_objects
Renamed.
Its easy to store them

2021-07-14 14:17 UTC, PopeyeTheSailorsCat commented on frontend/UI_client.py
> +            print(ex)
Actually this is my debug staff i forgot to delete.
I think it will be more convenient to leave it for others who will work with qt, not knowing that if something breaks inside the application, it crashes with an error code and says nothing. Instead of printing, I added logger.error and raise the Exception

2021-07-14 14:21 UTC, PopeyeTheSailorsCat commented on frontend/UI_client.py
> +    w_size, l_size = 800, 600  # ONLY FOR DEBUG
Done

2021-07-14 14:53 UTC, PopeyeTheSailorsCat commented on backend/server.py
> +    def create_update_response(request, humans) -> UpdateResponse:  # create pb2 object
While doing this I came across a problem
I gave all the response messages the Id of the received request, but the empty request does not have this. If you add this to it, there will be no difference between Empty and UpdateRequest

2021-07-14 16:48 UTC, PopeyeTheSailorsCat commented on frontend/UI_client.py
> +        return BuildingRectangle(rand_x, rand_y, rand_width, rand_length, DEFAULT_ANGLE)
Done this in order to complete the task

2021-07-14 16:48 UTC, PopeyeTheSailorsCat commented on frontend/UI_client.py
> +        return HumanDote(x, y, human_type)
Done this in order to complete the task

2021-07-14 16:52 UTC, PopeyeTheSailorsCat commented on frontend/UI_config_parser.py
> +        return processed_config
Will be done in future when config will be reworked

2021-07-14 17:03 UTC, PopeyeTheSailorsCat commented on backend/server.py
> +    def create_update_response(request, humans) -> UpdateResponse:  # create pb2 object
Done. Object for humans does not exist yet

2021-07-18 15:15 UTC, yarnaid commented on Makefile
> +	pyuic5 frontend/UI/infection-spread.ui -o frontend/UI/infection_spread_ui.py
I mean a separate target to start frontend

2021-07-18 15:17 UTC, merged