Feature/7 map method
yarnaid/infection_spread pull request #33
Opened 2021-08-29 16:06 UTC by YaroslavAggressive

2021-08-29 21:19 UTC, yarnaid requested changes

2021-08-29 21:19 UTC, yarnaid commented on backend/config_parser.py
> +    config_name: str = field(1, default=0)
is it ok default value 0 for str?

2021-08-29 21:19 UTC, yarnaid commented on backend/config_parser.py
> +    wall_length_divider: int = field(9, default=0)
do we need these default values? In protobuf you can omit them

2021-08-29 21:19 UTC, yarnaid commented on backend/map_generation.py
> +SERIALIZATION_FILE = "C:/Users/tyryk/PycharmProjects/infection_spread/tests/test_serialization.txt"
Please, don't store your local paths in the code. Use relative paths and `pathlib`

2021-08-29 21:19 UTC, yarnaid commented on backend/map_generation.py
> +        Filename for reading map settings
do we need this parameter in the message?

2021-08-30 10:59 UTC, YaroslavAggressive commented on backend/config_parser.py
> +    config_name: str = field(1, default=0)
Done

2021-08-30 10:59 UTC, YaroslavAggressive commented on backend/config_parser.py
> +    wall_length_divider: int = field(9, default=0)
Done

2021-08-30 10:59 UTC, YaroslavAggressive commented on backend/map_generation.py
> +        Filename for reading map settings
Done

2021-08-30 10:59 UTC, YaroslavAggressive commented on backend/map_generation.py
> +SERIALIZATION_FILE = "C:/Users/tyryk/PycharmProjects/infection_spread/tests/test_serialization.txt"
Done

2021-08-30 20:20 UTC, yarnaid requested changes

2021-08-30 20:20 UTC, yarnaid commented on backend/map_generation.py
> +print(ff)
please, remove this

2021-08-30 20:20 UTC, yarnaid commented on tests/test_backend.py
> +# testing dummy map
useless comment

2021-08-30 21:46 UTC, YaroslavAggressive commented on backend/map_generation.py
> +print(ff)
Done

2021-08-30 21:46 UTC, YaroslavAggressive commented on tests/test_backend.py
> +# testing dummy map
Done

2021-09-03 19:15 UTC, merged